spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/join
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/check/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: test-service
          uri: lb://TEST-SERVICE
          predicates:
            - Path=/api/test-service/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/test-service/(?<segment>.*), /$\{segment}
        - id: test-service
          uri: lb://TEST-SERVICE
          predicates:
            - Path=/api/test-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/test-service/(?<segment>.*), /$\{segment}
        - id: test-service
          uri: lb://TEST-SERVICE
          predicates:
            - Path=/api/test-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/test-service/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter
        - id: place-service
          uri: lb://PLACE-SERVICE
          predicates:
            - Path=/place-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/place-service/(?<segment>.*), /$\{segment}
        - id: place-service
          uri: lb://PLACE-SERVICE
          predicates:
            - Path=/place-service/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/place-service/(?<segment>.*), /$\{segment}
        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/api/review-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/review-service/(?<segment>.*), /$\{segment}
        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/api/review-service/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/review-service/(?<segment>.*), /$\{segment}
        - id: trip-service
          uri: lb://TRIP-SERVICE
          predicates:
            - Path=/api/trip-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/trip-service/(?<segment>.*), /$\{segment}
        - id: trip-service
          uri: lb://TRIP-SERVICE
          predicates:
            - Path=/api/trip-service/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/trip-service/(?<segment>.*), /$\{segment}
        - id: tag-service
          uri: lb://TAG-SERVICE
          predicates:
            - Path=/api/tag-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/tag-service/(?<segment>.*), /$\{segment}
        - id: tag-service
          uri: lb://TAG-SERVICE
          predicates:
            - Path=/api/tag-service/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/tag-service/(?<segment>.*), /$\{segment}
        - id: share-service
          uri: lb://SHARE-SERVICE
          predicates:
            - Path=/api/share-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/share-service/(?<segment>.*), /$\{segment}
        - id: share-service
          uri: lb://SHARE-SERVICE
          predicates:
            - Path=/api/share-service/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/share-service/(?<segment>.*), /$\{segment}
